language: python
python:
  - 3.5

services:
  - docker

install:
  - docker build -t paperless .
  - cp docker-compose.yml.example docker-compose.yml
  - cp docker-compose.env.example docker-compose.env
  - docker-compose up -d

script:
  - docker ps | grep -q paperless_webserver_1
  - docker ps | grep -q paperless_consumer_1
  - docker exec -e PAPERLESS_EMAIL_SECRET=paperless paperless_webserver_1 ./manage.py test
