# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_auto_20181007_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filenumber',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='foldernumber',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([('foldernumber', 'filenumber')]),
        ),
    ]
