# Generated by Django 2.0.10 on 2019-02-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '9001_folder_file_number'),
        ('documents', '0023_document_current_filename'),
    ]

    operations = [
    ]
